module Prefab
  class Feature123
    def value: -> String
  end
  class Config
    def self.feature_123: () -> Feature123
    def self.feature_456: () -> String
    def self.http_timeout: () -> Integer
    def self.http_retries: () -> Integer
    def self.db_host: () -> String
    def self.db_user: () -> String
  end
end
