# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prefab.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
require 'ratelimit_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cloud.prefab.domain.ConfigServicePointer" do
    optional :account_id, :int64, 1
    optional :start_at_id, :int64, 2
  end
  add_message "cloud.prefab.domain.ConfigDelta" do
    optional :account_id, :int64, 1
    optional :id, :int64, 2
    optional :key, :string, 3
    optional :value, :message, 4, "cloud.prefab.domain.ConfigValue"
  end
  add_message "cloud.prefab.domain.ConfigValue" do
    oneof :value do
      optional :int, :int64, 1
      optional :string, :string, 2
      optional :bytes, :bytes, 3
      optional :double, :double, 4
      optional :bool, :bool, 5
      optional :feature_flag, :message, 6, "it.ratelim.data.FeatureFlag"
    end
  end
  add_message "cloud.prefab.domain.ConfigDeltas" do
    repeated :deltas, :message, 1, "cloud.prefab.domain.ConfigDelta"
  end
end

module Cloud
  module Prefab
    module Domain
      ConfigServicePointer = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud.prefab.domain.ConfigServicePointer").msgclass
      ConfigDelta = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud.prefab.domain.ConfigDelta").msgclass
      ConfigValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud.prefab.domain.ConfigValue").msgclass
      ConfigDeltas = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud.prefab.domain.ConfigDeltas").msgclass
    end
  end
end
