# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: prefab.proto for package 'cloud.prefab.domain'

require 'grpc'
require 'prefab_pb'

module Cloud
  module Prefab
    module Domain
      module RateLimitService
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'cloud.prefab.domain.RateLimitService'

          rpc :LimitCheck, It::Ratelim::Data::LimitRequest, It::Ratelim::Data::LimitResponse
        end

        Stub = Service.rpc_stub_class
      end
      module ConfigService
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'cloud.prefab.domain.ConfigService'

          rpc :GetConfig, ConfigServicePointer, stream(ConfigDeltas)
          rpc :Upsert, ConfigDelta, ConfigServicePointer
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
